"""mensagem

Revision ID: 634bf1c86060
Revises: f37ca612dec0
Create Date: 2025-09-11 08:58:49.585002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634bf1c86060'
down_revision = 'f37ca612dec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('numero_paginas', sa.Integer(), nullable=True),
    sa.Column('editora', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro')
    # ### end Alembic commands ###
